name: Deploy

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: unnecessary

    - name: Setup SSH known_hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create .env file
      run: |
        touch .env
        echo "AUTH_TOKEN=${{ secrets.AUTH_TOKEN }}" >> .env
        echo "NODE_ENV=production" >> .env

    - name: Stop bot
      env:
        DOCKER_HOST: "ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}"
      run: docker compose down
      
    - name: Build bot
      env:
        DOCKER_HOST: "ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}"
      run: docker compose build

    - name: Start bot
      env:
        DOCKER_HOST: "ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}"
      run: docker compose up --detach
